# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12igzZ3LyN8OnbnRu30x7EPyZbI3ZgSXl
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

dataset = pd.read_csv('harga sepatu.csv')

dataset

"""##Splitting Training and Test Set
##Since we have a very small dataset, we will train our model with all availabe data.
"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

X = dataset.iloc[:,:3]

X

y = dataset.iloc[:,-1]

y

regressor.fit(X, y)

# Saving model to disk
pickle.dump(regressor, open('model.pkl','wb'))

# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[2, 9, 6]]))